// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaH2tMSzdGa35UV6bHXjB-qLQZpq8gjP8',
    appId: '1:500533961858:web:0fea2b30b7cfca4532009b',
    messagingSenderId: '500533961858',
    projectId: 'dr-ai-97349',
    authDomain: 'dr-ai-97349.firebaseapp.com',
    storageBucket: 'dr-ai-97349.firebasestorage.app',
    measurementId: 'G-PHRCCX07MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9VM5cufRJTr1UvYWJ_v7v1lsBD0-5auo',
    appId: '1:500533961858:android:0446456160899d1d32009b',
    messagingSenderId: '500533961858',
    projectId: 'dr-ai-97349',
    storageBucket: 'dr-ai-97349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOAYh5eh2XIWiAObgChYLNxgzvBZADfs',
    appId: '1:500533961858:ios:1ff1c2d04b0733cd32009b',
    messagingSenderId: '500533961858',
    projectId: 'dr-ai-97349',
    storageBucket: 'dr-ai-97349.firebasestorage.app',
    androidClientId: '500533961858-dh6eldva8vhpir8hi0kd0qggcvb9ufoq.apps.googleusercontent.com',
    iosClientId: '500533961858-dkiucertn2mihmebssnqd8u3h5kjd0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOAYh5eh2XIWiAObgChYLNxgzvBZADfs',
    appId: '1:500533961858:ios:1ff1c2d04b0733cd32009b',
    messagingSenderId: '500533961858',
    projectId: 'dr-ai-97349',
    storageBucket: 'dr-ai-97349.firebasestorage.app',
    androidClientId: '500533961858-dh6eldva8vhpir8hi0kd0qggcvb9ufoq.apps.googleusercontent.com',
    iosClientId: '500533961858-dkiucertn2mihmebssnqd8u3h5kjd0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaH2tMSzdGa35UV6bHXjB-qLQZpq8gjP8',
    appId: '1:500533961858:web:7b81b428e163897132009b',
    messagingSenderId: '500533961858',
    projectId: 'dr-ai-97349',
    authDomain: 'dr-ai-97349.firebaseapp.com',
    storageBucket: 'dr-ai-97349.firebasestorage.app',
    measurementId: 'G-KGJP0DCZ1H',
  );
}
